name: k6 Performance Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start Node.js app in background
        run: |
          node app.js &
          sleep 5

      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: performance-tests/test.js
